#!/bin/sh
# chkconfig: 345 30 70
# description: Call vproc to hide certain dangerous entries in /proc
# from vservers.
#

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovfixproc,v 1.1 2005/01/20 19:49:34 grisha Exp $

ETHIF=eth0

# See how we were called.
case "$1" in
  start)
	echo "Hiding proc entries from vservers using vproc"

	# hide everything
	for file in /proc/*; do 
	    setattr --admin --watch --hide $file > /dev/null 2>&1
	done

	# unhide only the bare minimum
	 for file in /proc/{*info,stat,uptime,loadavg,version,net,mounts}; do
	     setattr --~hide $file
	 done
	;;
  stop)
	# nothing to do here
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
	echo Not implemented
	;;
  force-reload)
	$0 stop
	$0 start
        ;;
  status)
	echo Not implemented
	;;
  *)
	echo "Usage: ohfixproc {start|stop|restart|reload|status}"
	exit 1
esac

exit 0




