#!/bin/sh
# chkconfig: 345 30 70
# description: This restores the context disk limits which should be \
#   periodically saved in /var/db/oh/disklimits by a cronjob calling ohdisk
#

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovresources,v 1.5 2005/11/17 21:31:16 grisha Exp $

DISKLIMITS=`python -c 'from openvps.host import cfg; print cfg.VAR_DB_OPENVPS'`/disklimits/disklimits
PREFIX=`python -c 'from openvps.host import cfg; print cfg.PREFIX'`

# See how we were called.
case "$1" in
  start)
	echo "Generating RSA key"
	$PREFIX/sbin/ovgenkey 

	echo "Restoring context disk limits"
	/bin/sh $DISKLIMITS

	;;
  stop)
	# nothing to do here
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
	echo Not implemented
	;;
  force-reload)
	$0 stop
	$0 start
        ;;
  status)
	echo Not implemented
	;;
  *)
	echo "Usage: ohdisklimit {start|stop|restart|reload|status}"
	exit 1
esac

exit 0




