#!/bin/sh

#
# Copyright 2006 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovcleanrebuilds,v 1.2 2006/03/08 15:00:11 grisha Exp $

# This script removes the .reuild* directories left after a VPS has
# been rebuilt.

VSERVERS=/vservers/
DAYS=2

REBUILDS=`find /vservers/ -maxdepth 1 -name ".rebuild*"`

for REBUILD in $REBUILDS ; do
    rm -rf "$REBUILD" > /dev/null 2>&1
    chattr -R -i "$REBUILD" > /dev/null 2>&1
    rm -rf "$REBUILD"
done

# just in case, fix flags in reference servers

REFROOTS=`python -c 'from openvps.host import cfg; print " ".join(cfg.REFROOTS)'`

for REFROOT in $REFROOTS ; do
    if [ -d $REFROOT ] ; then
	openvps fixflags $REFROOT > /dev/null 2>&1
    fi
done





