#!/usr/bin/env python

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovgenkey,v 1.2 2005/02/05 05:26:36 grisha Exp $

# regenrate the RSA key. we use a value that is known only for the
# duration of the machine's uptime for some added security

from openvps.common import crypto
from openvps.host import cfg

import time
import os
import grp

boottime = time.time() - float(open("/proc/uptime").read().split()[0])
boottime =  time.strftime("%Y-%M-%d-%H",(time.localtime(boottime)))

# generate and save private key

keypath = os.path.join(cfg.VAR_DB_OPENVPS, cfg.KEYFILE)
crypto.save_key(crypto.genkey(), keypath, boottime)

# make it readable only by apache group

apache_gid = grp.getgrnam('apache').gr_gid
os.lchown(keypath, os.stat(keypath).st_uid, apache_gid)
os.chmod(keypath, 0640)




